<h3>Saturday, August 30, 2014 / 2:00-5:00 p.m.</h3>
<b>Performers:</b> 
Jay Ottaway 2:00-3:00 p.m.
Sarah Blacker 3:00-4:00 p.m.
Phil Henry 4:00-5:00 p.m.
Saturday Night Jam Session 8:00 p.m. Hosted by Jay Ottaway at Frank's Tavern, Ludlow.
<h3>Sunday, August 31, 2014 / 2:00-5:00 p.m.</h3>
<b>Performers:</b> 
Chad Hollister 2:00-3:00 p.m.
Hayley Jane and the Primates 3:00-4:00 p.m.
Alastair Moock 4:00-5:00 p.m.

<hr />
<h2>Saturday, August 30, 2014 / 2:00-5:00 p.m.</h2>
<hr />

<dl><dt><img src="http://www.plymouthfolk.com/wp-content/uploads/2013/07/liz.jpg" alt="#####" width="150" />Jay Ottaway 2:00-3:00 p.m.</dt><dd>Jay Ottaway is an award-winning songwriter/producer who studied songwriting and blues guitar at the Berklee College of Music (Boston) and cut his teeth in Nashville as a singer-songwriter. He has been honored by American Songwriter Magazine, the USA Songwriting, International Songwriting, the U.K. Songwriting, and the Peacedriven Songwriting Contests, in addition to multiple awards from the Berklee College of Music, both as an arranger and a songwriter. He tours throughout Europe and the U.S. with his electric Jay Ottaway Band and in the U.S. as a solo acoustic act. He just released his second CD on the German label Cactus Rock Records entitled “Carry On.” He has co-produced the Plymouth Folk and Blues Festival since 2003. More info: <a href="http://www.jayottaway.com">www.jayottaway.com</a> </dd></dl>

<dl><dt><img src="http://www.plymouthfolk.com/wp-content/uploads/2013/07/bickhardt.jpg" alt="#####" width="150" />Sarah Blacker 3:00-4:00 p.m.</dt><dd>Sarah Blacker was just named Female Performer of the Year by the New England Music Awards. She also recently released her third CD and is receiving extensive airtime on many radio stations in New England. In addition she was the winner of the Radio 92.9 / Boch Subaru contest, named ‘Artist of the Year’ by My Rural Radio in 2011 and was runner up in the Limelight Magazine’s Video of the Year contest for her music video of ‘Knocked the Winds.’ Her music has been featured on MTV shows Jersey Shore and Friendzone and in 2013 she appeared as an emerging artist at the historic Falcon Ridge Folk Festival. Sarah has performed at SXSW, CMJ, as well as a sold-out tour of Germany, and has shared the stage with such artists as America, 10,000 Maniacs, Paula Cole, Sara Bareilles. Her entrancing voice, poignant emotionally charged lyrics, and mature songwriting have her on pace to go nowhere but up. More info: <a href="http://www.sarahblacker.com">www.sarahblacker.com</a></dd></dl>

<dl><dt><img src="http://www.plymouthfolk.com/wp-content/uploads/2013/07/danielle.jpg" alt="#####" width="150" />Phil Henry 4:00-5:00 p.m.</dt><dd>Phil Henry is an award-winning singer-songwriter and music educator from Rutland, Vermont. He is that rare contemporary folk artist who will impress you from every direction. There’s his sweet and strong voice, that intricate and flawless guitar work, and songs so rich and sweeping you’ll wish you wrote them yourself. He’s an old-school storyteller who builds songs from a place of honesty, without crossing over into the “too-much-information” of confessional songwriting. He sings his original, contemporary folk songs in coffeehouses, festivals, and house concerts across the Northeast and has showcased on national stages, such as the Kerrville Folk Festival and the Falcon Ridge Folk Festival. Phil has also won top honors in songwriting contests at the Susquehanna Music and Arts Festival and Vermont’s SolarFest. More info: <a href="http://www.philhenryband.com">www.philhenryband.com</a></dd></dl>

<dl><dt><img class="size-full wp-image-158 alignleft" title="Jay Ottaway" src="http://www.plymouthfolk.com/wp-content/uploads/2011/08/JayOttaway-ac.jpg" alt="" width="150" height="225" />Saturday Night Jam Session 8:00 p.m. Hosted by Jay Ottaway</dt><dd>
Jay Ottaway is an award-winning songwriter/producer who studied songwriting and guitar at the Berklee College of Music (Boston) and cut his teeth in Nashville as a singer-songwriter and producer. He has been honored by American Songwriter Magazine, The USA Songwriting Contest, The International Songwriting Contest, the U.K. Songwriting Contest, and the Peacedriven Songwriting Contest, and many others. He tours throughout Europe and the U.S. with his electric, Jay Ottaway Band, and as a solo acoustic act. He also has co- produced the Plymouth Folk and Blues Fest in Plymouth, Vermont since 2003.</dd></dl>

<hr />

<h2>Sunday, August 31, 2014 / 2:00-5:00 p.m.</h2>

<hr />

<dl><dt><img src="http://www.plymouthfolk.com/wp-content/uploads/2013/07/chelsea.jpg" alt="#####" width="150" />Chad Hollister 2:00-3:00 p.m.</dt><dd>Vermonter Chad Hollister is a voice for the POSITIVE. Chad’s music is a blend of unique melodies, grooves, lyrics, as well as his positive vision of Life. The music could be described like any of the great bands he has opened for or performed with, such as Bob Dylan, Tom Petty, Blues Traveler, Phish, Paul Simon, Little Feat, and many more. Yet people have also compared his music to Lenny Kravitz, Dave Mathews, Jack Johnson, and John Mayer. His single “Grow,” off his most recent record, has received radio airplay from VT to Colorado on over 120 stations. Through four albums and constant concert tours, Chad is continually finding new ways to connect to fans and spread his vision of American rock and roll from the sea and sand of CA and FL to the mountains of CO and VT. More info: <a href="http://www.chadmusic.com">www.chadmusic.com</a></dd></dl>

<dl><dt><img src="http://www.plymouthfolk.com/wp-content/uploads/2013/07/john-sarah.jpg" alt="#####" width="150" />Hayley Jane and the Primates 3:00-4:00 p.m.</dt><dd>Hayley Jane and the Primates are the 2014 New England Music Awards’ Americana/Roots Act of the Year! Their genre-bending sound and live performances have created a serious buzz in the Northeast. The Primates’ music draws inspiration from a variety of styles, including 60s/70s rock and pop, old musical theater, folk, blues, soul, reggae, psychedelic, funk, bluegrass, and country. Their catchy songs have been praised for successfully combining a diverse sound with clever, over-the-top lyrics and Vaudevillian style storytelling. Their on-stage energy, skilled musicianship, theatrics, and group improvisation take you over a landscape of emotion that will leave you wanting more. More info: <a href="http://www.hayleyjaneandtheprimates.com">www.hayleyjaneandtheprimates.com</a></dd></dl>

<dl><dt><img src="http://www.plymouthfolk.com/wp-content/uploads/2013/07/jarrod.jpg" alt="#####" width="150" />Alastair Moock 4:00-5:00 p.m.</dt><dd>Alastair Moock is a GRAMMY-nomiated singer-songwriter based in Boston. Since 1995, he has toured the U.S. and Europe, won top honors at many of the country’s most prestigious songwriting contests, and was nominated for a Boston Music Award for Outstanding Singer/Songwriter of the Year. The Boston Globe calls him “one of the town’s best and most adventurous songwriters” and The Washington Post says “every song is a gem.” Now nearly twenty years into his performing career, Alastair has managed to carve out a unique niche for himself: He is a songwriter committed to celebrating the roots of American music while knocking down the walls between different audiences, genres and musical traditions. In 2013 Alastair released Singing Our Way Through: Songs for the World’s Bravest Kids, an album which grew out of songs co-written with his daughter after she was diagnosed with leukemia in 2012 (she’s now doing great). Since then Moock has campaigned to bring this GRAMMY-nominated project to hospitals, clinics, and camps around the country. More info: <a href="http://www.moock.com">www.moock.com</a></dd></dl>